# Generated by Django 4.2 on 2023-05-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='imagens/logo/')),
                ('whatsapp', models.CharField(max_length=30)),
                ('instagram', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
                ('cnpj_cpf', models.CharField(max_length=18)),
            ],
        ),
    ]
