# Generated by Django 4.2 on 2023-04-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_cores_tamanhos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='cor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.cores'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tamanho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.tamanhos'),
        ),
    ]
