# Generated by Django 4.2 on 2023-04-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produtos_cor_alter_produtos_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.IntegerField(null=True),
        ),
    ]
