# Generated by Django 4.2 on 2023-05-06 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_imagens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='produtos',
            name='obs',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.marcas'),
        ),
    ]
