# Generated by Django 4.2 on 2023-05-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_marcas_alter_produtos_obs_alter_produtos_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='imagem',
            field=models.ImageField(upload_to='./static/imagens/'),
        ),
    ]
