# Generated by Django 4.2 on 2023-05-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_imagens_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='imagem',
            field=models.ImageField(upload_to='imagens/'),
        ),
    ]
