# Generated by Django 4.2 on 2023-05-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_imagens_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='capa',
            field=models.ImageField(blank=True, upload_to='produtos/imagens/capas/'),
        ),
    ]
