# Generated by Django 4.2 on 2023-05-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_alter_categoria_options_categoria_categoria_mae'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'verbose_name_plural': 'subcategorias'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='categoria_mae',
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='subcategoria_mae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='produtos.subcategoria'),
        ),
    ]
