# Generated by Django 4.2 on 2023-05-09 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_menus_alter_dados_loja_options'),
        ('produtos', '0015_categoria_subcategorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus_categoria', to='loja.menus'),
        ),
    ]
