# Generated by Django 4.2 on 2023-05-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_categoria_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagens',
            name='nome',
        ),
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('avaliacao', models.CharField(max_length=140, null=True)),
                ('estrelas', models.IntegerField()),
                ('produtos', models.ManyToManyField(blank=True, to='produtos.produtos')),
            ],
        ),
    ]
