# Generated by Django 4.2 on 2023-05-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0017_remove_imagens_nome_avaliacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='subcategoria_mae',
        ),
    ]
