# Generated by Django 4.2 on 2023-05-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0018_remove_subcategoria_subcategoria_mae'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='subcategoria_fk',
        ),
        migrations.AddField(
            model_name='produtos',
            name='subcategoria_fk',
            field=models.ManyToManyField(blank=True, to='produtos.subcategoria'),
        ),
    ]
