# Generated by Django 4.2 on 2023-06-16 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0019_remove_produtos_subcategoria_fk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=8)),
                ('complemento', models.CharField(max_length=50, null=True)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pedido', models.FloatField(null=True)),
                ('data', models.DateField()),
                ('cliente_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('endereco_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.enderecos')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.IntegerField()),
                ('vlr_produto', models.FloatField(null=True)),
                ('observacao', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('produto_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produtos_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.produtos')),
            ],
        ),
    ]
