# Generated by Django 4.2 on 2023-05-24 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lista_desejos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_desejos',
            name='usuario_fk',
        ),
        migrations.AddField(
            model_name='lista_desejos',
            name='usuario_fk',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
