# Generated by Django 4.2 on 2023-05-24 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lista_desejos', '0002_remove_lista_desejos_usuario_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_desejos',
            name='usuario_fk',
        ),
        migrations.AddField(
            model_name='lista_desejos',
            name='usuario_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
