# Generated by Django 4.2 on 2023-05-25 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0019_remove_produtos_subcategoria_fk_and_more'),
        ('lista_desejos', '0003_remove_lista_desejos_usuario_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_desejos',
            name='produtos_fk',
        ),
        migrations.AddField(
            model_name='lista_desejos',
            name='produtos_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.produtos'),
        ),
    ]
